### ISSUE TITLE
problem with your asset in marketplace

### ISSUE THREAD

**Issue by adnoh** [yvvan/WfcEnvironmentGeneratorLite#1]
hello yvvan, one can't "purchase" the asset in marketplace. there happens an unknown error.
I guess you should inform epic about that.

**Comment by yvvan** [comment]
@adnoh Thanks for your message. I've reported a "bug" to https://marketplacehelp.epicgames.com. Hope they solve it.

**Comment by adnoh** [comment]
@yvvan now it works. strange. didn't work via webbrowser or launcher. will try it out ;) thank you
